default: &default
  adapter: postgresql
  encoding: unicode
  host: db-rails
  username: postgres
  password: SUPER_SECRET_PASSWORD
  pool: 5

development:
  <<: *default
  database: app_development


test:
  <<: *default
  database: app_test